# Generated by Django 4.2.5 on 2023-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=32, verbose_name='标识id')),
                ('nickname', models.CharField(default='anonymous', max_length=32, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('addr', models.CharField(default='none', max_length=127, verbose_name='所处地')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='性别')),
                ('avatarUrl', models.CharField(default='/', max_length=255, verbose_name='头像url')),
                ('avatar', models.ImageField(upload_to='images/')),
                ('phone', models.CharField(default='none', max_length=15, verbose_name='手机号码')),
                ('intro', models.TextField(default='none', max_length=255, verbose_name='个人简介')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
