# Generated by Django 4.2.5 on 2023-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_addr_user_age_user_gender_user_intro_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abstract',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
