# Generated by Django 4.2.5 on 2023-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(default='/', max_length=255, verbose_name='头像url'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='anonymous', max_length=32, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default='', max_length=32, verbose_name='标识id'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(default='none', max_length=127, verbose_name='所处地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(default='none', max_length=255, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='none', max_length=15, verbose_name='手机号码'),
        ),
    ]
